import os
import json
from pathlib import Path
from discord import Embed

CUR_RAIDS_PATH = Path("cur_raids.json")

if CUR_RAIDS_PATH.exists():
    cur_raids = json.load(open(CUR_RAIDS_PATH, "r"))
else:
    cur_raids = {}


class Config:
    def __init__(self):
        self.CONFIG_PATH = "config.json"
        self.CONFIG = self._get_config()
        self.PREFIX = self.CONFIG["prefix"]
        self.TOKEN = self._get_env_var("TOKEN")
        self.CLASSES = self.CONFIG["classes"]
        self.ENGLISH_DICTIONARY = [
            "of",
            "and",
            "to",
            "in",
            "that",
            "it",
            "for",
            "on",
            "you",
            "with",
            "as",
            "be",
            "he",
            "at",
            "by",
            "are",
            "have",
            "this",
            "not",
            "but",
            "from",
            "had",
            "they",
            "his",
            "or",
            "which",
            "she",
            "we",
            "there",
            "were",
            "her",
            "one",
            "all",
            "do",
            "their",
            "if",
            "will",
            "would",
            "what",
            "so",
            "can",
            "when",
            "more",
            "up",
            "who",
            "out",
            "said",
            "about",
            "them",
            "some",
            "its",
            "could",
            "into",
            "then",
            "other",
            "him",
            "two",
            "time",
            "only",
            "like",
            "my",
            "than",
            "well",
            "now",
            "your",
            "me",
            "over",
            "may",
            "just",
            "new",
            "these",
            "also",
            "any",
            "people",
            "first",
            "very",
            "know",
            "see",
            "after",
            "should",
            "such",
            "where",
            "because",
            "how",
            "most",
            "back",
            "get",
            "way",
            "our",
            "down",
            "made",
            "right",
            "between",
            "much",
            "work",
            "think",
            "many",
            "being",
            "even",
            "those",
            "go",
            "ive",
            "no",
            "before",
            "yeah",
            "through",
            "good",
            "ire",
            "three",
            "make",
            "us",
            "last",
            "year",
            "still",
            "must",
            "take",
            "ill",
            "own",
            "off",
            "here",
            "both",
            "say",
            "too",
            "oh",
            "come",
            "used",
            "going",
            "little",
            "use",
            "government",
            "same",
            "under",
            "each",
            "day",
            "however",
            "might",
            "another",
            "man",
            "yes",
            "put",
            "world",
            "again",
            "long",
            "need",
            "against",
            "want",
            "life",
            "while",
            "thought",
            "part",
            "never",
            "old",
            "look",
            "home",
            "something",
            "house",
            "since",
            "course",
            "number",
            "why",
            "end",
            "away",
            "place",
            "different",
            "found",
            "great",
            "really",
            "local",
            "went",
            "within",
            "four",
            "case",
            "left",
            "next",
            "without",
            "came",
            "always",
            "set",
            "system",
            "though",
            "give",
            "during",
            "around",
            "few",
            "small",
            "mean",
            "although",
            "rather",
            "social",
            "group",
            "given",
            "find",
            "second",
            "until",
            "five",
            "quite",
            "company",
            "party",
            "far",
            "point",
            "important",
            "less",
            "state",
            "public",
            "later",
            "information",
            "high",
            "general",
            "national",
            "often",
            "once",
            "help",
            "school",
            "fact",
            "money",
            "seen",
            "example",
            "head",
            "further",
            "whether",
            "business",
            "best",
            "night",
            "area",
            "better",
            "mm",
            "taken",
            "water",
            "done",
            "large",
            "having",
            "form",
            "order",
            "thing",
            "yet",
            "family",
            "possible",
            "perhaps",
            "hand",
            "early",
            "already",
            "face",
            "young",
            "john",
            "side",
            "nothing",
            "days",
            "development",
            "week",
        ]

    def _get_config(self):
        return json.load(open(self.CONFIG_PATH, "r"))

    def _get_env_var(self, var_name):
        return os.environ[var_name]


def get_cogs():
    out_list = []

    for cog_file in os.walk(os.path.dirname(os.path.abspath(__file__)) + "/cogs/"):
        for cog in cog_file[2]:
            if cog[-3:] == ".py":
                out_list.append(f"cogs.{cog[:-3]}")

    return out_list


def load_message(cog_name):
    print(f"\t✓ Loaded {cog_name} cog!")
